steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
          '-t',
          'gcr.io/$PROJECT_ID/gcs_cloud_run:$_IMAGE_TAG',
          '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gcs_cloud_run:$_IMAGE_TAG']
substitutions:
  _IMAGE_TAG: latest